### ISSUE TITLE
Please consider making a tagged release

### ISSUE THREAD

**Issue by petecooper** [oracle/bpftune#101]
Firstly, thank you for `bpftune` - it's excellent.

Respectfully, please consider tagged release(s).

This would be beneficial for change control and sign off, compiling from the latest repo contents is preventing me deploying this on live servers. If there was a tagged / versioned release, I can use that more freely.

Thank you for your consideration.

**Comment by alan-maguire** [comment]
sure thing; we're planning a release soon and we'll tag it appropriately.
