### ISSUE TITLE
Replace -march=native from Makefile

### ISSUE THREAD

**Issue by ptr1337** [oracle/bpftune#50]
Hi,

As already stated in the PR (https://github.com/oracle/bpftune/pull/49) this should be replaced with more default -march, since compiling this package to repositories will break the package, if the instruction set used from the builder is not supported from the user.

Since I don't feel well in providing that many information's for the registration, please any oracle member should work on this

**Comment by alan-maguire** [comment]
we also build bpftune for aarch64, so maybe this will help cross-compile to x86_64 on other architectures, but it breaks existing native builds on aarch64 so is a step backwards. it would be nice to enable cross-compile, but the solution you've proposed breaks native compile so isn't workable.

**Comment by aviallon** [comment]
@alan-maguire `-march=native` is not necessary to build on any GCC supported architecture.

What it does is to enable the use of instructions specific to the builder's CPU, which may make the binary non-functional on any other machine, including those of the same micro-architecture but of a different model.

See : https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#index-march-16

**Comment by bzed** [comment]
@ptr1337 replacing it with x86-64 makes things even worse as it will break building bpftune on all other architectures.

I can't speak for oracle linux or redhat, but for Debian:

Each Debian architecture has a baseline indicating the oldest or least capable CPU on which the architecture can be used. The baseline can change between Debian releases. The baseline is mostly defined by the gcc-N package, which is configured to produce baseline binaries when options like -march= are not used.

https://wiki.debian.org/ArchitectureSpecificsMemo has the details.

So I would suggest to drop -march.

**Comment by bzed** [comment]
Actually src/Makefile doesn't use -march anymore, so I guess this bug can be closed.

**Comment by alan-maguire** [comment]
true; the Makefiles were reworked so I'll close this one out..
