### ISSUE TITLE
Bpftune crashes when suspending

### ISSUE THREAD

**Issue by Tungsten842** [oracle/bpftune#53]
1) Press the power button to suspend the laptop.
2) The bpftune service stops.

```
❯ journalctl -u bpftune.service
Aug 19 10:10:50 nixos-dell systemd[1]: Started BPF-based auto-tuning of system parameters.
Aug 19 10:10:50 nixos-dell bpftune[7957]: bpftune works fully
Aug 19 10:10:50 nixos-dell bpftune[7957]: bpftune supports per-netns policy (via netns cookie)
Aug 19 10:11:41 nixos-dell bpftune[7957]: ring_buffer__poll: Interrupted system call
Aug 19 10:11:43 nixos-dell systemd[1]: bpftune.service: Deactivated successfully.
Aug 19 10:11:43 nixos-dell systemd[1]: bpftune.service: Consumed 4.180s CPU time, no IO, no IP traffic.
```
OS: nixos-unstable

**Comment by alan-maguire** [comment]
a few questions
- does the service start again on resume? is it unusual for services to stop in suspend?
- the above log is expected and doesn't indicate crash (just that the polling was interrupted by service stopping). we see the same on normal exit. were there other signs of crash like coredump?

**Comment by alan-maguire** [comment]
i've removed the error reporting for the case where a signal is received now: https://github.com/oracle/bpftune/pull/55

**Comment by Tungsten842** [comment]
> #56 fixes the issue for me (tested via "systemctl suspend"). I've merged it into main; can you try rebuilding/retesting? thanks!

It works now🎉
