### ISSUE TITLE
ip_frag_tuner.so: No such file or directory

### ISSUE THREAD

**Issue by andrey-admin** [oracle/bpftune#72]
After build last tree, got this in syslog:

Sep  8 12:06:24 nginx-01 bpftune[77649]: bpftune works fully
Sep  8 12:06:24 nginx-01 bpftune[77649]: bpftune supports per-netns policy (via netns cookie)
Sep  8 12:06:25 nginx-01 bpftune[77649]: could not open /proc/sys/net/ipv6/neigh/default/gc_interval (netns fd 0) for reading: No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: could not open /proc/sys/net/ipv6/neigh/default/gc_stale_time (netns fd 0) for reading: No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: could not open /proc/sys/net/ipv6/neigh/default/gc_thresh1 (netns fd 0) for reading: No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: could not open /proc/sys/net/ipv6/neigh/default/gc_thresh2 (netns fd 0) for reading: No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: could not open /proc/sys/net/ipv6/neigh/default/gc_thresh3 (netns fd 0) for reading: No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: could not open /proc/sys/net/ipv6/route/max_size (netns fd 0) for reading: No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: could not open /proc/sys/net/ipv6/ip6frag_high_thresh (netns fd 0) for reading: No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: error reading tunable 'net.ipv6.ip6frag_high_thresh': No such file or directory
Sep  8 12:06:25 nginx-01 bpftune[77649]: error initializing '/usr/lib64/bpftune//ip_frag_tuner.so: No such file or directory

But file on place and seems ok:
# ldd /usr/lib64/bpftune//ip_frag_tuner.so
        linux-vdso.so.1 (0x00007ffc9ef5b000)
        libbpf.so.0 => /lib/x86_64-linux-gnu/libbpf.so.0 (0x00007fb42b35c000)
        libbpftune.so.0.1.3 => /usr/lib64/libbpftune.so.0.1.3 (0x00007fb42ac00000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb42a800000)
        libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007fb42b33e000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb42b322000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007fb42b315000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb42b3b3000)

**Comment by alan-maguire** [comment]
thanks for the report! is IPv6 disabled perhaps? i can make the tunable optional like we did for some of the others if so..

**Comment by andrey-admin** [comment]
Yes, with that fix all started ok. 

Thanks!
